### ISSUE TITLE
How do I run the binary file on mac?

### ISSUE THREAD

**Issue by chen-bowen** [MykalMachon/RBC-LunchMoney#2]
I tried double click it looks like it's taking me to this file with strange characters. Did I do anything wrong here?
<img width="665" alt="image" src="https://github.com/MykalMachon/RBC-LunchMoney/assets/18410378/3b3cb3fd-64d6-4f02-9f6a-fe196d749b7c">

**Comment by MykalMachon** [comment]
Hi @chen-bowen, thanks for filing an issue.
I don't have a mac, but here's the basics of running the file in a Linux environment. It should be mostly the same. 

1. Make sure you have an RBC export downloaded and you have a LunchMoney API key available.
2. Open the folder you'd like to keep the binary in 
3. Open your mac's terminal in that folder
4. Download the latest release from the releases page or by running curl in your terminal `curl -LO https://github.com/MykalMachon/RBC-LunchMoney/releases/download/v0.4/rbclm`
5. In the terminal, add the run permission to the binary with `chmod +x ./rbclm` 
6. In the terminal, run the binary by typing `./rbclm`. This should start the importer for you. 

Let me know if you have any issues; I've been using this weekly for months with no issue but I'm on Windows + Linux

**Comment by MykalMachon** [comment]
Closing; feel free to re-open if you have any other questions.
